### ISSUE TITLE
The script exits at this line without notice. 

### ISSUE THREAD

**Issue by startergo** [RefindPlusRepo/RefindPlusUDK#4]
https://github.com/dakanji/Refind-UDK/blob/585e63db2985b09c4a6580647449d3edd564479f/000-BuildScript/RepoUpdater.sh#L47

**Comment by dakanji** [comment]
Not clear what you mean.

Is it that the directory is present and it fails or that it is not but there is no notice when it fails to find it?

**Comment by startergo** [comment]
No it just exits at that line without actually updating. So if I remove the "; exit 1" or replace it with || exit 1 in both instances  then it finishes.

**Comment by dakanji** [comment]
Got it. Will fix
